version: 2.1

executors:
  ghctl:
    docker:
      - image: amirashad/ghctl:0.3.1

commands:
  validate:
    steps:
      - run:
          name: ghctl version
          command: ghctl --version
      - run:
          name: yq version
          command: yq --version
  apply:
    steps:
      - run:
          name: apply
          command: ./apply.sh

jobs:
  validate:
    executor: ghctl
    steps:
      - checkout
      - validate
  apply:
    executor: ghctl
    steps:
      - checkout
      - validate
      - apply

workflows:
  GitOps-RepoCreator_workflow:
    jobs:
      - validate
      - apply:
          context: GITHUB
          requires:
            - validate
          filters:
            branches:
              only: master
