version: 2.1

executors:
  ghctl:
    docker:
      - image: amirashad/ghctl

commands:
  install:
    steps:
      - run:
          name: ghctl version
          command: |
            ghctl --version
  apply:
    steps:
      - run:
          name: apply repo yaml
          command: ./apply.sh

jobs:
  validate:
    executor: ghctl
    steps:
      - checkout
      - install
  apply:
    executor: ghctl
    steps:
      - checkout
      - install
      - apply

workflows:
  GitOps-RepoCreator_workflow:
    jobs:
      - validate
      - apply:
          context: GITHUB
          requires:
            - validate
          # filters:
          #   branches:
          #     only: master
